using System;
using System.Collections.Generic;
using System.Linq;
using System.IO;
using System.Text;

namespace StellaQL
{
    public abstract class Tutorial
    {
        public static void ToContents(StringBuilder contents)
        {
            contents.AppendLine(@"---------------------------------------------------------------");
            contents.AppendLine(@"StellaQL チュートリアル");
            contents.AppendLine(@"Tutorial of StellaQL");
            contents.AppendLine(@"---------------------------------------------------------------");
            contents.AppendLine(@"    作者  : 高橋 智史 (ハンドルネーム: むずでょ)");
            contents.AppendLine(@"    Author: TAKAHASHI Satoshi (Handle. Muzudho)");
            contents.AppendLine(@"---------------------------------------------------------------");
            contents.AppendLine(@"");
            contents.AppendLine(@"");
            contents.AppendLine(@"手順1");
            contents.AppendLine(@"Step 1");
            contents.AppendLine(@"");
            contents.AppendLine(@"    あなたのUnityプロジェクトのバックアップは取っておいてください。");
            contents.AppendLine(@"    Please keep a backup of your data.");
            contents.AppendLine(@"");
            contents.AppendLine(@"    エラー等で中断した際、データの復元機能は付いていません。");
            contents.AppendLine(@"    There is no rollback at error suspension.");
            contents.AppendLine(@"");
            contents.AppendLine(@"");
            contents.AppendLine(@"手順2");
            contents.AppendLine(@"Step 2");
            contents.AppendLine(@"");
            contents.AppendLine(@"    既にやっていると思いますが、メニューから[Window] - [State Machine Command Line (StellaQL)] をクリックしてください。");
            contents.AppendLine(@"    I think you are doing it already. [Window] - [State Machine Command Line (StellaQL)] is here.");
            contents.AppendLine(@"");
            contents.AppendLine(@"");
            contents.AppendLine(@"手順3");
            contents.AppendLine(@"Step 3");
            contents.AppendLine(@"");
            contents.Append(@"    """); contents.Append(FileUtility_Engine.PATH_ANIMATOR_CONTROLLER_FOR_DEMO_TEST); contents.AppendLine(@"""ファイルを開いてださい。");
            contents.Append(@"    Please, open """); contents.Append(FileUtility_Engine.PATH_ANIMATOR_CONTROLLER_FOR_DEMO_TEST); contents.AppendLine(@""".");
            contents.AppendLine(@"");
            contents.Append(@"    また、その "); contents.Append(Path.GetFileName(FileUtility_Engine.PATH_ANIMATOR_CONTROLLER_FOR_DEMO_TEST)); contents.AppendLine(" ファイルを [Animation Controller Drag & Drop] 枠にドラッグ＆ドロップしてください。");
            contents.Append(@"    And Drag&Drop the "); contents.Append(Path.GetFileName(FileUtility_Engine.PATH_ANIMATOR_CONTROLLER_FOR_DEMO_TEST)); contents.AppendLine(" file to [Animation Controller Drag & Drop] box.");
            contents.AppendLine(@"");
            contents.AppendLine(@"");
            contents.AppendLine(@"手順4 (任意)");
            contents.AppendLine(@"Step 4 (Option)");
            contents.AppendLine(@"");
            contents.AppendLine(@"    始める前に、開発者が夜中に StellaQL を壊していないか、テストすることができます。");
            contents.AppendLine(@"    Before you begin, developers can test whether they break StellaQL at midnight.");
            contents.AppendLine(@"");
            contents.AppendLine(@"        [Window] - [Editor Tests Runner] ... [StellaQL] - [StellaQLTest].");
            contents.AppendLine(@"        [Window] - [Editor Tests Runner] ... [StellaQL] - [StellaQLTest].");
            contents.AppendLine(@"");
            contents.AppendLine(@"    そして [Run All]を押してください。チェックが全て緑色ならＯＫです。");
            contents.AppendLine(@"    And [Run All]. Please, click is all greens.");
            contents.AppendLine(@"");
            contents.AppendLine(@"    ただし、既に Demo_Zoo を編集していた場合は結果が異なります。");
            contents.AppendLine(@"    However, if you have already edited Demo_Zoo, the result will be different.");
            contents.AppendLine(@"");
            contents.AppendLine(@"");
            contents.AppendLine(@"手順5");
            contents.AppendLine(@"Step 5");
            contents.AppendLine(@"");
            contents.AppendLine(@"    次の文をクエリー・テキストボックスに入力してください。");
            contents.AppendLine(@"    Please enter the following statement in the Query text box.");
            contents.AppendLine(@"");
            contents.AppendLine(@"    TRANSITION INSERT");
            contents.AppendLine(@"    FROM ""Base Layer\.Cat""");
            contents.AppendLine(@"    TO   ""Base Layer\.Dog""");
            contents.AppendLine(@"");
            contents.AppendLine(@"    そして、Executeボタンを押してください。");
            contents.AppendLine(@"    Then press the Execute button.");
            contents.AppendLine(@"");
            contents.AppendLine(@"    Base Layer.Catステートから Base Layer.Dog ステートへ線が引かれていることを確認してください。");
            contents.AppendLine(@"    Please confirm that a line is drawn from Base Layer.Cat state to Base Layer.Dog state.");
            contents.AppendLine(@"");
            contents.AppendLine(@"");
            contents.AppendLine(@"手順6");
            contents.AppendLine(@"Step 6");
            contents.AppendLine(@"");
            contents.AppendLine(@"    次の文をクエリー・テキストボックスに入力してください。");
            contents.AppendLine(@"    Please enter the following statement in the Query text box.");
            contents.AppendLine(@"");
            contents.AppendLine(@"    # Hi!");
            contents.AppendLine(@"    TRANSITION INSERT");
            contents.AppendLine(@"    FROM ""Base Layer\.Foo""");
            contents.AppendLine(@"    TO   ""Base Layer\..*[Nn].*""");
            contents.AppendLine(@"");
            contents.AppendLine(@"    そして、Executeボタンを押してください。");
            contents.AppendLine(@"    Then press the Execute button.");
            contents.AppendLine(@"");
            contents.AppendLine(@"    Fooステートから、名前に N が含まれるステートに線が引かれました。");
            contents.AppendLine(@"    From the Foo state, a line was drawn in the state whose name contained N.");
            contents.AppendLine(@"");
            contents.AppendLine(@"    でも、こんな線要らないですね。");
            contents.AppendLine(@"    But, I do not need this line.");
            contents.AppendLine(@"");
            contents.AppendLine(@"");
            contents.AppendLine(@"手順6");
            contents.AppendLine(@"Step 6");
            contents.AppendLine(@"");
            contents.AppendLine(@"    次の文をクエリー・テキストボックスに入力してください。");
            contents.AppendLine(@"    Please enter the following statement in the Query text box.");
            contents.AppendLine(@"");
            contents.AppendLine(@"    # This line is a comment!");
            contents.AppendLine(@"    TRANSITION DELETE");
            contents.AppendLine(@"    FROM ""Base Layer\.Foo""");
            contents.AppendLine(@"    TO   ""Base Layer\..*""");
            contents.AppendLine(@"");
            contents.AppendLine(@"    そして、Executeボタンを押してください。");
            contents.AppendLine(@"    Then press the Execute button.");
            contents.AppendLine(@"");
            contents.AppendLine(@"    Foo ステートから伸びている線が全て消えました。");
            contents.AppendLine(@"    All the lines extending from the Foo state disappeared.");
            contents.AppendLine(@"");
            contents.AppendLine(@"    Cat ステートから Dog ステートへの線はつながったままなことを確認してください。");
            contents.AppendLine(@"    Please confirm that the line from Cat state to Dog state remains connected.");
            contents.AppendLine(@"");
            contents.AppendLine(@"");
            contents.AppendLine(@"その他のクエリーは、コマンド　リファレンス　ボタンを押して調べてください。");
            contents.AppendLine(@"For other queries, please check by pressing the command reference button.");
            contents.AppendLine(@"");
            contents.AppendLine(@"");
            contents.AppendLine(@"サンキュー☆（＾ｑ＾）");
            contents.AppendLine(@"Thank you.");
        }
    }
}
